### ISSUE TITLE
Polymer (custom) elements are not indented properly

### ISSUE THREAD

**Issue by mikevaleriano** [Glavin001/atom-beautify#1270]
# Description

Custom elements are not formatted while the rest of the HTML file is formatted when beautifying an HTML file, which is the format for Polymer elements. Anything inside the `template` tag is ignored by atom-beautify and only the opening tag is indented.
# Input Before Beautification

This is what the code looked like before:

```
<dom-module id="sample-element">
<template>
<div>Hello world</div>
</template>
    <script>
        Polymer({
            is: 'sample-element'
        });
    </script>
</dom-module>
```
# Expected Output

The beautified code should have looked like this:

```
<dom-module id="sample-element">
    <template>
        <div>Hello world</div>
    </template>
    <script>
        Polymer({
            is: 'sample-element'
        });
    </script>
</dom-module>
```
# Actual Output

The beautified code actually looked like this:

```
<dom-module id="sample-element">
    <template>
<div>Hello world</div>
</template>
    <script>
        Polymer({
            is: 'sample-element'
        });
    </script>
</dom-module>
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/anonymous/b1603f59f154de9ef6e426cfaec3d4fd
# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
I can reproduce at http://jsbeautifier.org/

Notifying @bitwiseman

**Comment by darwinserrano** [comment]
In version 0.29.10 of atom-beautify this doesn't happen. It's a reference for find the solution.

**Comment by Glavin001** [comment]
Looks like it has been resolved. Closing as a resolved, JS-Beautify bug.

**Comment by jfletcher-nuxeo** [comment]
This is happening again, currently have the problem in 0.29.17 whereas 0.29.10 still works fine.

**Comment by yanlee26** [comment]
same here...
And how to fix it???
@mikevaleriano  @Glavin001  @jfletcher-nuxeo

**Comment by mikevaleriano** [comment]
@yanlee26  Yeah, switch to vscode.

**Comment by szeck87** [comment]
When Polymer 3.0 is released, element definition will be significantly different as it will use ES6 modules versus HTML Imports since the latter wasn't adopted in many browsers.  I don't know how much effort would be put into fixing jsbeautify or prettydiff to fix issues with 1.0 and 2.0 with 3.0 on the horizon.  PrettyDIff does a little bit better job for 2.0 elements, but still not perfect as you can see with the naming of the element in the script tag:

```
<dom-module id="sample-element">
    <template>
        <div>Hello world</div>
    </template>
    <script>
        Polymer({is: 'sample-element'});
    </script>
</dom-module>
```

https://www.polymer-project.org/blog/2017-08-23-hands-on-30-preview.html

**Comment by jfletcher-nuxeo** [comment]
@yanlee26 I'm back to using `0.29.10` as neither JSBeautify nor PrettyDiff can correctly support both Polymer code and aligned attributes :(
