### ISSUE TITLE
LaTex Beautify failed with "Can't use string ("0") as a HASH ref while "strict refs"

### ISSUE THREAD

**Issue by nasyxx** [Glavin001/atom-beautify#1564]
# Description

When I used `latexindent xxxx.tex` in terminal, nothing wrong.

But when I use Atom-Beautify in atom, an error happened.

The trace back here:

```
Error: Can't use string ("0") as a HASH ref while "strict refs" in use at /usr/local/texlive/2016/texmf-dist/scripts/latexindent/LatexIndent/HorizontalWhiteSpace.pm line 30.
  at /Users/Nasy/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:295:27
  at tryCatcher (/Users/Nasy/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/Users/Nasy/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:510:31)
  at Promise._settlePromise (/Users/Nasy/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:567:18)
  at Promise._settlePromise0 (/Users/Nasy/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
  at Promise._settlePromises (/Users/Nasy/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
  at Async._drainQueue (/Users/Nasy/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
  at Async._drainQueues (/Users/Nasy/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
  at Async.drainQueues (/Users/Nasy/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
  at process._tickCallback (internal/process/next_tick.js:103:7)
```

# Input Before Beautification

This is what the code looked like before:

```
\documentclass{article}

\usepackage[footnotes,definitionLists,hashEnumerators,smartEllipses, hybrid]{markdown}



\begin{document}

\begin{markdown}
hello

Head 01
=========

Yoooo

\end{markdown}

\end{document}
```

# Expected Output

The beautified code should have looked like this:

```
\documentclass{article}

\usepackage[footnotes,definitionLists,hashEnumerators,smartEllipses, hybrid]{markdown}



\begin{document}

\begin{markdown}
	hello

	Head 01
	=========

	Yoooo

\end{markdown}

\end{document}
```

# Actual Output

The beautified code actually looked like this:

```
Error
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/nasyxx/48f15cecc0d4e319bd81c32447a17b84

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues

**Comment by Glavin001** [comment]
From the logs:

> 2017-03-21T08:32:22.857Z - debug: [beautifiers/beautifier.coffee] spawn /Library/TeX/texbin/latexindent 0=-o, 1=-s, 2=-l, 3=-c=/var/folders/sn/pv0g90nd1j1cw20ct_7bpl100000gn/T/latex117221-33672-9t1vwi.te31tyy14i, 4=/var/folders/sn/pv0g90nd1j1cw20ct_7bpl100000gn/T/latex117221-33672-9t1vwi.te31tyy14i/latex.tex, 5=/var/folders/sn/pv0g90nd1j1cw20ct_7bpl100000gn/T/latex117221-33672-9t1vwi.te31tyy14i/latex.tex

The command used is:

```
/Library/TeX/texbin/latexindent -o -s -l -c=/var/folders/sn/pv0g90nd1j1cw20ct_7bpl100000gn/T/latex117221-33672-9t1vwi.te31tyy14i /var/folders/sn/pv0g90nd1j1cw20ct_7bpl100000gn/T/latex117221-33672-9t1vwi.te31tyy14i/latex.tex /var/folders/sn/pv0g90nd1j1cw20ct_7bpl100000gn/T/latex117221-33672-9t1vwi.te31tyy14i/latex.tex
```

Could you try the following:

```
/Library/TeX/texbin/latexindent -o -s -l -c=LOG_DIR/ FILENAME.tex FILENAME.tex
```

See https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/latex-beautify.coffee#L60-L66 for how the arguments are generated.

**Comment by Nil-Zil** [comment]
I also have the same problem, I found that it occur after I update my latexindent to version 3.0, the last version (2.2) has no such problem. Here is my `indent.log` use the way you mentioned.

```
latexindent version 3.0, a script to indent .tex files
	latexindent lives here: /usr/local/texlive/2016/texmf-dist/scripts/latexindent/
	Mon Apr 10 01:26:31 2017
Processing switches
	-l|--localSettings: Read localSettings YAML file
	-o|--outputfile: output to file
	-c|--cruft: cruft directory
Directory for backup files and indent.log: ./
YAML settings read
	Reading defaultSettings.yaml from /usr/local/texlive/2016/texmf-dist/scripts/latexindent/defaultSettings.yaml
	Home directory is /Users/Qi (didn't find either indentconfig.yaml or .indentconfig.yaml)
	To specify user settings you would put indentconfig.yaml here: /Users/Qi/indentconfig.yaml
	Alternatively, you can use the hidden file .indentconfig.yaml as: /Users/Qi/.indentconfig.yaml
	WARNING yaml file not found: ./localSettings.yaml not found
	Proceeding without it.
List of items: item|myitem (see itemNames)
looking for VERBATIM commands (see verbatimCommands)
looking for FILE CONTENTS environments (see fileContentsEnvironments)
	looking for filecontents*:1 environments
	looking for filecontents:1 environments
	\begin{document} found in body (after searching for filecontents)-- assuming that a preamble exists
	Custom replacement text routine for preamble preamble
	preamble found: LatexIndent::Preamble=HASH(0x7ffb97039a58)
	replaced with ID: LTXIN-TK-preamble1-END
	
	\begin{document}
	NOT storing LTXIN-TK-preamble1-END for indentation -- will store as VERBATIM object (see indentPreamble)
Phase 1: searching for objects
	looking for ENVIRONMENTS
	looking for IFELSEFI
	looking for HEADINGS (chapter, section, part, etc)
	looking for COMMANDS and key = {value}
	looking for SPECIAL begin/end
Objects have been found.
Operating on: masterdocument
Number of children:
	1
Phase 2: finding surrounding indentation
Phase 3: indenting objects
Phase 4: final indentation check
Output routine
	Outputting to file -s
--------------
Please direct all communication/issues to: 
	https://github.com/cmhughes/latexindent.pl
```

**Comment by Glavin001** [comment]
>  I found that it occured after I updated my latexindent to version 3.0, the last version (2.2) has no such problem.

Sounds like a breaking change to `latexindent` from v2 to v3. I would be happy to approve a Pull Request if you can figure out what the new `latexindent` v3 needs as arguments. The applicable section of code is https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/latex-beautify.coffee#L61-L65 . Let me know if you have any Atom-Beautify specific questions!

**Comment by nasyxx** [comment]
Hi, I tried this just now:

```
/Library/TeX/texbin/latexindent -o -s -l -c=logs/ 0001.tex 000101.texs
```

And here is the [indent.log](https://gist.github.com/nasyxx/2eb1efe95687b7eb4bd8ab14f747a1af)

**Comment by Nil-Zil** [comment]
I have found that the problem is because of [this](https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/latex-beautify.coffee#L29) line, the suggested way to write is
```coffeescript
removeTrailingWhitespace:
    beforeProcessing: 0
    afterProcessing: 1
```
This seems to work. Can you change that?

**Comment by bemeurer** [comment]
I can confirm this. Having the same issue here.

**Comment by orlandini** [comment]
same issue here.

**Comment by laebhh** [comment]
same here. :-(

**Comment by Nil-Zil** [comment]
Well, what I can suggest is that you firstly downgrade to latexindent 2.2, and wait it to be fixed. I have tried to fix it (it seems not hard), but because of not familiar with coffeescript, something went wrong.

**Comment by cmhughes** [comment]
Just seen this; apologies that the update broke this part of your script.

Have you had any luck fixing your implementation? I can confirm that you need 
```
removeTrailingWhitespace:
    beforeProcessing: 0
    afterProcessing: 1
```
It looks like you could re-use some of the code you've written
```
removeTrailingWhitespace:\n
etc
```
While you're editing, you could also remove the following lines:
```
alwaysLookforSplitBraces: #{+options.always_look_for_split_braces}
alwaysLookforSplitBrackets: #{+options.always_look_for_split_brackets}
```
as these keys no longer do anything, from V3.0 onwards.

If you have any other `latexindent.pl` related issues, do feel free to ping me (@cmhughes)
Best
Chris (author of `latexindent.pl`, https://github.com/cmhughes/latexindent.pl)

**Comment by cmhughes** [comment]
PS: I don't recommend downgrading below V3.0 for `latexindent.pl` :)

**Comment by cmhughes** [comment]
At time of writing, I see that this is one of 463 issues, so I understand that it may not get fixed quickly. As such, if a few people could help me test, I think I could provide a fix at my end for `latexindent.pl`.

So, @nasyxx , @Nil-Zil , @bemeurer , @orlandini , @laebhh, could you commit to helping me test? It wouldn't involve much, just the following steps:
- clone the `develop` branch of `latexindent.pl`
- making sure that your `path` variable is set up to use this version and *not* your currently installed version
- checking that any fixes I provide fix this issue.

If you could let me know, I could get to work -- I'm hopeful that it won't take much at my end, but I'll need your feedback for testing.
Best
Chris

**Comment by Nil-Zil** [comment]
@cmhughes Yes, I would like to help you.

**Comment by bemeurer** [comment]
@cmhughes  On it right now.

**Comment by bemeurer** [comment]
@cmhughes Tested here and the problem persists
```
Can't use string ("0") as a HASH ref while "strict refs" in use at /home/meurer/src/latexindent.pl/LatexIndent/HorizontalWhiteSpace.pm line 30.
Can't use string ("0") as a HASH ref while "strict refs" in use at /home/meurer/src/latexindent.pl/LatexIndent/HorizontalWhiteSpace.pm line 30.
```

**Comment by Nil-Zil** [comment]
Well, I have tried to modify `~/.atom/packages/atom-beautify/src/languages/latex.coffee` from
```coffeescript
remove_trailing_whitespace:
      type: 'boolean'
      default: false
      description: "Remove trailing whitespace"
```
to
```coffeescript
remove_trailing_whitespace:
      type: 'array'
      default: ['beforeProcessing: 0', 'afterProcessing: 1']
      description: "Remove trailing whitespace"
```
and in `~/.atom/packages/atom-beautify/src/beautifiers/latex-beautify.coffee` I modified this line from
```coffeescript
removeTrailingWhitespace: #{+options.remove_trailing_whitespace}
```
to
```coffeescript
removeTrailingWhitespace:\n #{+options.remove_trailing_whitespace}
```
the problem remains:
```
Can't use string ("0") as a HASH ref while "strict refs" in use at /usr/local/texlive/2017/texmf-dist/scripts/latexindent/LatexIndent/HorizontalWhiteSpace.pm line 30.
```

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/e86406f2cf4b85b439839a6cbf1097f8e2c8acfa I've updated `HorizontalWhiteSpace.pm` to allow `removeTrailingWhitespace` to be specified as a number.

@bemeurer @Nil-Zil can you pull from `develop` (https://github.com/cmhughes/latexindent.pl/tree/develop) and use the *original* version `~/.atom/packages/atom-beautify/src/beautifiers/latex-beautify.coffee` and let me know if this works?

**Comment by Nil-Zil** [comment]
Yes, it works! @cmhughes

**Comment by Nil-Zil** [comment]
Yes, this time it does not have such error. But actually my file is not indented: it does not change at all.

**Comment by cmhughes** [comment]
Is this a latexindent issue, or an atom issue?

**Comment by cmhughes** [comment]
I think I see the problem: the -o switch changed a little bit in v3.0 of latexindent.pl, and needs the output file to be specified next to the -o switch, for example:


latexindent.pl myfile.tex -o output.tex

So, if you move the -o switch in between the two @texFile statements, that might work.

Let me know if this fixes it or not.

**Comment by Nil-Zil** [comment]
@cmhughes Yes, it works. Thank you for your remind!

**Comment by cmhughes** [comment]
Great! So, I propose the following:

- I'll get the develop version of latexindent packaged and released in the next few days
- once I've done that, you submit a pull request to this project with your fix

Does that sound ok?

**Comment by Nil-Zil** [comment]
Yes, no problem.

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/682de1ec6622c94df2a4160873e07bd8e7717d96 the `latexindent.pl` part of this issue is resolved.

@Nil-Zil over to you. I would like to go on record as saying that I don't recommend using `latexindent.pl` in the following way:
```
latexindent.pl myfile.tex -o myfile.tex
```
as this by passes the backup procedure. Instead, if you want to overwrite a file with `latexindent.pl`, I'd recommend using
```
latexindent.pl myfile.tex -w
```

Please do feel free to tag me (@cmhughes) for future `latexindent.pl` related issues.

**Comment by Nil-Zil** [comment]
My pleasure. As long as CTAN update to 3.2.2, I will try to modify it.

**Comment by cmhughes** [comment]
I uploaded it to ctan tonight -- it usually takes a day or so.

**Comment by Glavin001** [comment]
Published to v0.30.4

**Comment by HR** [comment]
Still experiencing with `v0.30.6` on High Sierra after fixing issue #1792 by running

```bash
sudo cpan Unicode::GCString
sudo cpan App::cpanminus
sudo cpan YAML::Tiny
sudo perl -MCPAN -e 'install "File::HomeDir"'
```

**Comment by szeck87** [comment]
@HR Are you receiving the same error in this issue (Can't use string ("0") as a HASH ref) or the one in #1792 (Can't locate YAML/Tiny.pm in @INC)?

**Comment by HR** [comment]
Yes, here is the stacktrace

```
Error: Can't use string ("0") as a HASH ref while "strict refs" in use at /usr/local/texlive/2017/texmf-dist/scripts/latexindent/LatexIndent/HorizontalWhiteSpace.pm line 30.
    at /Users/Habib/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:182:27
    at tryCatcher (/Users/Habib/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Habib/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/Habib/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/Habib/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/Habib/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/HR/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/HR/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/HR/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by cmhughes** [comment]
What version of latexindent do you have?

**Comment by HR** [comment]
latexindent.pl version 3.0.2

**Comment by szeck87** [comment]
@HR it sounds like this issue was fixed with 3.2.2, can you upgrade to that and try?

**Comment by cmhughes** [comment]
This was fixed as of 3.2.2 (I think); latest version is 3.3.

**Comment by HR** [comment]
It works. Thanks, everyone.

**Comment by maikol-solis** [comment]
I'm having a similar issue in Opensuse Leap 15. I guess that could be something with the `latexindent` version. If yes, how could fix it? Thanks. 

`latexindent.pl version 3.1`

`atom-beautify v0.32.5 (2018-05-28)`

```
Can't use string ("1") as a HASH ref while "strict refs" in use at /usr/share/texmf/scripts/latexindent/LatexIndent/HorizontalWhiteSpace.pm line 30.
Can't use string ("1") as a HASH ref while "strict refs" in use at /usr/share/texmf/scripts/latexindent/LatexIndent/HorizontalWhiteSpace.pm line 30.
Hide Stack Trace
Error: Can't use string ("1") as a HASH ref while "strict refs" in use at /usr/share/texmf/scripts/latexindent/LatexIndent/HorizontalWhiteSpace.pm line 30.
    at /home/maikol/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:183:23
    at tryCatcher (/home/maikol/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/maikol/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/maikol/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/maikol/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/maikol/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/maikol/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/maikol/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/maikol/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by cmhughes** [comment]
Have you tried updating latexindent?

**Comment by maikol-solis** [comment]
@cmhughes  Yes I did it and worked! 

However, I have to install the Tumbleweed version of latexindent into Leap 15. I don't think that I will cause many troubles, but I mention it for the record.

**Comment by cmhughes** [comment]
What is Tumbleweed?

**Comment by bemeurer** [comment]
@cmhughes The rolling-release variant of OpenSUSE.

@maikol-solis That's not surprising, I'd imagine OpenSUSE, like Ubuntu, keeps fairly out-of-date TeXLive versions on their respective stable editions. It's very annoying.
