### ISSUE TITLE
Beautify adds extra space in HTML properties

### ISSUE THREAD

**Issue by Markko** [Glavin001/atom-beautify#231]
Changes: 
```html
<input type="submit" value="Submit"> 
```

to: 
```html
<input type="submit " value="Submit ">
```
This is breaking the submit button

**Comment by Glavin001** [comment]
*Please use code blocks*, triple backticks (`). I have fixed your Issue contents above.

---

[HTML Beautification is handled by `js-beautify](https://github.com/Glavin001/atom-beautify/blob/master/lib/language-options.coffee#L423). ~~Please forward this issue over to https://github.com/beautify-web/js-beautify~~.
I have tested your code on their website and it appears to work.

Could you please provide more information:
- Atom version
- Atom Beautify version
- file name (with extension) - this helps me confirm that Atom is treating it as the grammar `HTML` and not something else that *would* error

**Comment by Glavin001** [comment]
We can reopen this with some more information. Thank you.

**Comment by blindfish3** [comment]
Is there an option to disable the addition of spaces around "quotes"?  I couldn't find one.  For my sins I have to work with an HTML templating tool that depends on "quotes "within" quotes":

```<meta property="version" content="<t4 type="meta" meta="version" />" />```

Beautify helpfully inserted spaces - where any sane person *would* expect them - and this broke the attributes in the template tag:

```<meta property="version" content="<t4 type=" meta " meta=" version " />" />```

So not a problem with Beautify and I'm not trying to revive this issue; but the symptoms are close enough that this seemed an appropriate place to post this; and the option would resolve the issue for the OP and others having similar issues.

**Comment by xinthose** [comment]
This is still happening for `data-role="button"` --> `data-role="button "`, as well as for classes on elements.

**Comment by mkreyman** [comment]
Same here, it breaks my phoenix templates (.eex files) by adding extra spaces inside quotes:
```
<link rel="stylesheet" href="<%= static_path(@conn, " /css/app.css ") %>">

```
