### ISSUE TITLE
atom-beautify sometimes erases entire file

### ISSUE THREAD

**Issue by muppetjones** [Glavin001/atom-beautify#335]
I just upgraded to the latest (v27, I think), and now the "beautification" sometimes deletes everything in the editor window. Usually, this occurs when saving a file that is already saved, but it's not all the time.

So far, I have only used the latest version with python, but I was getting a similar issue with HTML files where `tidy` was removing all django calls (until I used a package to change the filetype to "HTML (django)"). I believe that these are separate issues, but they have related symptoms.

**Comment by Glavin001** [comment]
Saving seems to have bugs ( #326 , etc). I'll get back to you when I've fixed those bugs and maybe it'll fix this too. Thanks for letting me know.

**Comment by zachguo** [comment]
yeah, I can confirm, when using Python autopep8.

**Comment by Glavin001** [comment]
Could you update to v0.27.1 and let me know if that resolves anything for you. Thanks.

/cc #314

**Comment by muppetjones** [comment]
Just updated and tried saving multiple times. The problem still occurs, though maybe 1 in 10 or 20. I don't see a trigger, yet. I'll keep coding and update if I have anything else.

Thanks for fixing it so quickly!

**Comment by zachguo** [comment]
I still have the problem. Every time I made new edits, and `command + shift + p` then run `Atom Beautify: Beautify Editor`, the whole page would be erased.

**Comment by Glavin001** [comment]
> Every time

@zachguo could you run `Help Debug Editor`?

**Comment by zachguo** [comment]
I just ran `Atom Beautify: Help Debug Editor`, then atom complained `Editor is not responding`. So I restarted Atom and everything works now....
I'll post it here if I run into the issue again.

**Comment by Glavin001** [comment]
Okay, let me know if this arises again. Thanks!

**Comment by muppetjones** [comment]
So far, I have not run into the problem again. Thanks @Glavin001 !!

**Comment by muppetjones** [comment]
I've started seeing this problem much more frequently again (every other save or more) in the latest version (0.28.5). I saw it once every 10 saves or so in the previous version.

**Comment by Glavin001** [comment]
Let me know if you have something that can consistently reproduce this. I'd like to resolve it for good.

**Comment by hz** [comment]
I confirmed this.  main.c file was about 800 lines. After I pressed ctrl+s many times, it was emptied. Should we add one uuid as the suffix to the temp file? (atom-beautify version is 0.29.7 and atom version is 1.73.)
![screenshot from 2016-05-03 15-59-41](https://cloud.githubusercontent.com/assets/63441/14978112/238777a2-114c-11e6-9e47-330b55042da7.png)
